application: gcdc2013-grow
version: beta
api_version: 1
runtime: python27
threadsafe: true

libraries:

- name: pycrypto
  version: latest
- name: jinja2
  version: "2.6"

handlers:

- url: /_ah/admin/interactive.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /.*
  script: growedit.main.application

skip_files:

- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?utils/.*
- .*/ace-builds/(kitchen-sink|src|src-min|src-noconflict|textarea)/.*
- .*_test.*
- .*/tests/.*
