application: grow-prod
version: dev
api_version: 1
runtime: python27
threadsafe: true

builtins:

- deferred: on

libraries:

- name: pycrypto
  version: latest
- name: jinja2
  version: "2.6"
- name: lxml
  version: "latest"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.1.1"

handlers:

- url: /_ah/admin/interactive.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

- url: /_grow/public
  static_dir: growedit/pod/public

- url: /template
  static_dir: growedit/pod/public/template

- url: /.*
  script: growedit.main.application

#pagespeed:
#
#  domains_to_rewrite:
#  - http://grow-beta.appspot.com
#  - https://grow-beta.appspot.com
#
#  url_blacklist:
#  - http://*.p.*.appspot.com/*
#  - http://dev.*.appspot.com/*
#  - https://dev.*.appspot.com/*
#
#  enabled_rewriters:
#  - CollapseWhitespace
#  - CombineJs
#  - JsOptimize
#  - MinifyCss
#  - ProxyJs
#
#  disabled_rewriters:
#  - InlinePreviewImages
#  - LazyloadImages
#  - ProxyImages

skip_files:

- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?utils/.*
- .*/Jinja2-2.6/.*
- .*/ace-builds/(kitchen-sink|src|src-min|src-noconflict|textarea)/.*
- .*/appengine-ndb-experiment/.*
- .*/boto/bin/.*
- .*/demos/.*
- .*/doc/.*
- .*/docs/.*
- .*/examples/.*
- .*/experimental/.*
- .*/java/.*
- .*/jinja2/.*
- .*/samples/.*
- .*/submodules/paste/.*
- .*/test/cases/.*
- .*/tests/.*
- .*/webapp-improved/.*
- .*/webapp-improved/lib/babel/.*
- .*/webob/.*
- .*/werkzeug/docs/.*
- .*/werkzeug/examples/.*
- .*/werkzeug/testsuite/.*
- .*Mako-0.4.1/test/.*
- .*_test.*
